// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhgNpWcFQnkjg_iHkamGggqLzmSDnZrPQ',
    appId: '1:254788754945:web:fbf6cc24456116ca566a00',
    messagingSenderId: '254788754945',
    projectId: 'doan-64004',
    authDomain: 'doan-64004.firebaseapp.com',
    storageBucket: 'doan-64004.appspot.com',
    measurementId: 'G-PN5HNQ8BDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgIgIzp2HSfh8Q8t0nafwhHc5ikOCN_OQ',
    appId: '1:254788754945:android:20055129b452f752566a00',
    messagingSenderId: '254788754945',
    projectId: 'doan-64004',
    storageBucket: 'doan-64004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRomanIYzxhVkyn3OKJaWKUF_fNgUzD8k',
    appId: '1:254788754945:ios:9c7d43da451f89eb566a00',
    messagingSenderId: '254788754945',
    projectId: 'doan-64004',
    storageBucket: 'doan-64004.appspot.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRomanIYzxhVkyn3OKJaWKUF_fNgUzD8k',
    appId: '1:254788754945:ios:80fd418675286917566a00',
    messagingSenderId: '254788754945',
    projectId: 'doan-64004',
    storageBucket: 'doan-64004.appspot.com',
    iosBundleId: 'com.example.food.RunnerTests',
  );
}
